### ISSUE TITLE
infografia de realidad aumentada

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Abraham890#1]
[Infografía Realidad_Aumentada_Abraham Reyes Ortiz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-Abraham890/files/10828419/Infografia.Realidad_Aumentada_Abraham.Reyes.Ortiz.pdf)

**Comment by bg55-a** [comment]
calificacion: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
